thegeeklab/hugo-geekdoc

package.json

When using themes through git submodule some steps need to be ran in CI. One of these being the `gulp default` run. By adding this to the package.json CI setups for Hugo can use `npm i && npm run gulp default` instead of having to install gulp separately.

Add gulp to package.json scripts for ease of CI.

---

layouts/partials/head.html

When using baseURL in order to place the site into a subdirectory, fonts are not found because they are not placed in the root directory. Function relURL should also be used for fonts path resolution.

Relative URL resolution for fonts

---

exampleSite/content/usage/configuration.md
layouts/shortcodes/toc-tree.html

If an item of a toc-tree has a description flag, append it with a colon as prefix.
For instance:
```
...
{{< toc-tree >}}
```
```
- - - 
title: Item
description: Item description
- - - 
```
Will be shown as follows:

Allow description text in toc-tree items

---

assets/js/search-data.js
assets/js/search.js
exampleSite/content/usage/configuration.md

Titles in search results have not context. For example, if I have multiple "Getting Started" pages, all the results are going to be the same. This PR is to be able to give more context to search results:
If you activate this behaviour in your config file:
```
...
params:
...
geekdocSearch: true
geekdocSearchShowParent: true
```
Then, first parent is shown as prefix in search results:
* `geekdocSearchShowParent: false` (default and current approach):
* `geekdocSearchShowParent: true`:

Allow geekdocSearchShowParent

---

exampleSite/content/usage/configuration.md
layouts/shortcodes/toc-tree.html

I want to display a toc-tree in the page but not in the side bar. `geekdocHiddenInPage` param allows us to do that.
For instance:
```
---
name: Extra1
weight: ...
geekDocHidden: true
geekDocHiddenInPage: false
---
```
```
{{< toc-tree >}}
```
With this feature, you will see Extra1 in the page but not in the sidebar.
**Behaviour:**
`geekDocHidden=true` takes always precedence. `geekDocHiddenInPage` applies only when `geekDocHidden=false`  and the default value is `geekDocHiddenInPage=true` to be used only if you want to use.

Allow geekdocHiddenInPage as Page parameter

---

assets/js/groupBy.min.js
assets/js/search.js
src/sass/_base.scss

If `GeekdocSearchShowParent` param is set to true, group all results in the search under their parents. As a bonus, the search results list has been made a dropdown which shows up if there are any results and if the input is focused.
- Closes #37

Group search by sections

---

src/sass/_defaults.scss
src/sass/_normalize.css

Fixes https://github.com/thegeeklab/hugo-geekdoc/issues/57

fix: set line-height in normalized h1 to avoid overlapping

---

layouts/partials/site-header.html
src/sass/_base.scss

If you want add another logo it could be useful to change the size of it
with a custom css overwrite. With the old version this isn't possible
because the size defined in the img tag is always more significant. This
commit removes the height and width from the img tag and moves it to the
_base.scss file.

move logo size to _base.scss

---

exampleSite/content/_index.md
exampleSite/content/usage/getting-started.md
layouts/404.html
layouts/_default/baseof.html
layouts/partials/head/favicons.html
layouts/partials/head/meta.html
layouts/partials/head/others.html

Fixes: #96 
Description:
- Title will use format `<Page Title> | <Site Name>` except error and home page
- Description will use (first found):
- .Description
- [.Summary](https://gohugo.io/content-management/summaries/)
- .Site.Params.description
- .Site.Title

fix: rework site header for better title and decription handling

---

exampleSite/static/custom.css
exampleSite/static/custom.css.example
src/sass/_base.scss
src/sass/_chroma_base.scss
src/sass/_chroma_dark.scss
src/sass/_chroma_light.scss
src/sass/_markdown.scss
src/sass/main.scss

Fixes: #118 
The max-height for code block can be set via CSS variable `--code-max-height` in [custom.css](https://geekdocs.de/features/theming/). The default will remain to be `auto`.

feat: add css variable to set max height for code blocks

---

.dictionary
assets/js/search.js
exampleSite/content/_index.md
exampleSite/content/shortcodes/buttons.md
exampleSite/content/usage/configuration.md
layouts/_default/baseof.html

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/128

feat: add page parameter geekdocNav to disable navigation sidebar

---

exampleSite/content/usage/configuration.md
layouts/partials/menu-bundle.html
layouts/partials/menu-filetree.html

This allows setting `.Site.Params.GeekdocCollapseAllSections` which then
behaves as if you would have set `.Page.Params.geekdocCollapseSection`
in all sections.
It is a hard positive switch, so you can not override it per section
once enabled.

feat: collapse every section

---

layouts/partials/site-header.html

On a geekdoc-based site I run (outfox.wiki), I had changed the header to use a larger logo, and hid the site title because it was redundant to said logo. However, I still wanted the text to be visible on mobile, which required some CSS to specifically target the site title text. So I did this.
Simple little QoL tweak.

feat: Add CSS span to site title

---

layouts/partials/content.html
src/sass/_markdown.scss

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/176

fix: add div wrapper around markdown tables to allow overflows

---

layouts/partials/page-header.html

Using path.Join cleans up the line a bit and also avoids a current issue Windows users have using this theme, per https://github.com/gohugoio/hugo/issues/8885.
In the event no change is done to Hugo (and I assume the change won't be done since it's a very low-level functionality change), this at least helps this implementation and solves https://github.com/thegeeklab/hugo-geekdoc/issues/185

Use path.Join on "Edit this page" hyperlink

---

exampleSite/config.yaml
layouts/partials/head/others.html

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/201
Feeds are not implemented for this theme.

chore: remove rss link from header

---

exampleSite/content/shortcodes/includes.md

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/273

docs: document how to use different type in include shortcode

---

package.json

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/320

fix: use shx in npm scripts to fix cross-platform commands

---

layouts/partials/head/schema.html

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/317
Prevent failing builds if `tags` in the front matter is an empty string, e.g. `tags:` or `tags: ''`. It will still fail if tags is a non-empty string, e.g. `tags: Foo` but that's expected.

fix: prevent failing build if tags is an empty string

---

.gitignore
exampleSite/.gitignore
layouts/partials/page-header.html

**Documentation at https://geekdocs.de:**
The links [Edit page] located top right are currently broken on all pages. This PR fixes this issue.

fix: fix broken `Edit Page` links

---

.gitignore
exampleSite/config/_default/params.yaml
exampleSite/content/en/usage/configuration.md
layouts/partials/page-header.html

BREAKING CHANGE: With support of the multilingual mode, we broke the `edit page` links, as the content directory was statically hard-coded into the `GeekdocEditPath` parameter. To get the correct content directory, regardless of the language or a disabled multilingual mode, we now use Hugo's built-in `.Site.Params.contentDir` parameter. Therefor, you have to remove the hard-coded `/content` part from the `geekdocEditPath` parameter in the configuration of your project.

fix: fix edit page link and auto-detect contentDir

---

exampleSite/layouts/shortcodes/sprites.html
i18n/de.yaml
i18n/en.yaml
i18n/zh-cn.yaml
layouts/404.html
layouts/_default/_markup/render-heading.html
layouts/_default/terms.html
layouts/partials/language.html
layouts/partials/menu-bundle.html
layouts/partials/menu-extra.html
layouts/partials/menu-filetree.html
layouts/partials/page-header.html
layouts/partials/posts/metadata.html
layouts/partials/search.html
layouts/partials/site-footer.html
layouts/partials/site-header.html
layouts/shortcodes/icon.html
package-lock.json
src/js/copycode.js
src/sass/_base.scss
src/sass/_mobile.scss

BREAKING CHANGE: The class `.icon` was renamed to `.gdoc-icon` to avoid conflicts.
Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/378

refactor: rename class .icon to .gdoc-icon

---

exampleSite/content/en/shortcodes/images/_index.md
layouts/shortcodes/img.html

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/489
The size `origin` will embed the image as it is without rescaling.

feat: add origin size to image shortcode

---

exampleSite/content/en/shortcodes/propertylist.md
exampleSite/data/properties/demo.yaml
layouts/shortcodes/propertylist.html

BREAKING CHANGE: To enable sorting of elements in the `properties` shortcode, it was necessary to change the structure of the properties file. Due to this change, the `properties` object now requires a list of maps instead of a map. A [sample file](https://raw.githubusercontent.com/thegeeklab/hugo-geekdoc/main/exampleSite/data/properties/demo.yaml) can be found in the repository.

feat: add option to sort items in properties shortcode

---

src/js/colorTheme.js
src/js/mermaid.js

Write the color mode to the browser's local storage only if the user has explicitly requested it by pressing the button.

fix: dont write color mode defaults to local storage

---

exampleSite/content/en/usage/configuration.md
layouts/partials/head/others.html
src/js/app.js
src/js/colorTheme.js
src/sass/_base.scss
webpack.config.js

Adds a site parameter `geekdocDarkModeToggle` to enable or disable the JavaScript based dark mode toggle.

feat: add option to enable or disable the dark mode toggle button

---

layouts/_default/_markup/render-codeblock-mermaid.html

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/538
Site variables in markdown render hooks or partials need to be accessed via global `site` function or `.Page` object.

fix: fix access to data assets in render hook

---

layouts/_default/_markup/render-codeblock-mermaid.html

As we use `.Page.Site` in other places of the theme, already stick to this method instead of the global `site` function.

use .Page.Site instead of site to access data assets

---

src/sass/_color_mode.scss

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/530

fix: improve color of links within hints in dark mode

---

layouts/_default/_markup/render-heading.html

This is a Goldmark supported [feature](https://github.com/yuin/goldmark/#attributes) that isn’t reflected in GeekDoc theme.
This PR **only** adds support for custom heading CSS classes (`.className` and `class="class1 class2"`). Custom ids are not supported, nor any other custom attribute (`#id` and `attrName=attrValue`).

feat: add support for custom heading CSS class

---

.drone.yml
README.md
exampleSite/content/en/_index.md
layouts/partials/page-header.html
theme.toml

BREAKING CHANGE: The `Edit page` uses the `hugo.WorkingDir` function of Hugo, which was introduced in v0.112.0. Due to this change, the minimum Hugo version for the theme has been raised accordingly.
Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/663

fix: utilize hugo.WorkingDir for a reliable edit page link

---

layouts/shortcodes/expand.html

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/666
Partially reverts: https://github.com/thegeeklab/hugo-geekdoc/pull/415
I was not able to reproduce the original formatting issue. If it occurs again, we need to find a better solution and document it.

fix: remove htmlUnescape from expand shortcode

---

src/sass/_base.scss

On Safari the :activation-off triggers before the a-href hits. The result is that the searchbox will disapear before the new page is called. Fixed by replacing :active with :hover

Fixed CSS issue with Safari

---

exampleSite/content/en/shortcodes/buttons.md
exampleSite/content/en/shortcodes/columns.md
exampleSite/content/en/shortcodes/expand.md
exampleSite/content/en/shortcodes/hints.md
exampleSite/content/en/shortcodes/icons.md
exampleSite/content/en/shortcodes/images/_index.md
exampleSite/content/en/shortcodes/includes.md
exampleSite/content/en/shortcodes/katex.md
exampleSite/content/en/shortcodes/mermaid.md
exampleSite/content/en/shortcodes/progress.md
exampleSite/content/en/shortcodes/propertylist.md
exampleSite/content/en/shortcodes/tabs.md
exampleSite/content/en/shortcodes/toc-tree.md
exampleSite/content/en/shortcodes/toc.md
exampleSite/data/properties/shortcode-buttons.yaml
exampleSite/data/properties/shortcode-columns.yaml
exampleSite/data/properties/shortcode-hints.yaml
exampleSite/data/properties/shortcode-images.yaml
exampleSite/data/properties/shortcode-includes.yaml
exampleSite/data/properties/shortcode-katex.yaml
exampleSite/data/properties/shortcode-mermaid.yaml
exampleSite/data/properties/shortcode-progress.yaml
exampleSite/data/properties/shortcode-propertylist.yaml
exampleSite/data/properties/shortcode-toc.yaml

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/731

docs: use a propertylist to document shortcode attributes

---

.gitsv/config.yml
layouts/shortcodes/propertylist.html
src/sass/_shortcodes.scss

BREAKING CHANGE: The way anchors are generated for properties of a propertylist has changed to be unique, even if the shortcode is used multiple times on a page.

fix: generate unique properties anchor

---

.lighthouserc.yml
exampleSite/content/en/usage/configuration.md
layouts/404.html
layouts/partials/head/others.html
layouts/partials/microformats/schema.html
layouts/partials/search.html
layouts/partials/site-header.html

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/756

fix: replace `.Site.BaseURL` by recommended alternatives

---

layouts/partials/menu-bundle.html

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/737

fix: fix missing icon on collabsible bundle menus

---

exampleSite/content/en/usage/getting-started.md

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/784

docs: explain `buildDrafts` flag in getting started guide

---

layouts/shortcodes/img.html

The image shortcode as still preprocessed all image resources even if the size was set to `origin` which results in unintentional long build times.
Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/816

fix: skip image processing if size is origin

---

layouts/partials/language.html
layouts/partials/microformats/opengraph.html
layouts/partials/microformats/twitter_cards.html

With newer versions of Hugo, we get the following warning messages
> WARN  deprecated: .Site.IsMultiLingual was deprecated in Hugo v0.124.0 and will be removed in a future release. Use hugo.IsMultilingual instead.
WARN  deprecated: .Site.Social was deprecated in Hugo v0.124.0 and will be removed in a future release. Use .Site.Params instead.
**More information**: 
- https://github.com/gohugoio/hugo/issues/12224 
- https://gohugo.io/methods/site/ismultilingual/
- https://github.com/gohugoio/hugo/issues/12228

fix: replace deprecated `.Site.IsMultiLingual` and `.Site.Social`

---

exampleSite/config/_default/params.yaml
exampleSite/content/en/usage/configuration.md
layouts/_default/single.html
layouts/partials/page-metadata.html

Add new site- and page-parameter `geekdocPageLastmod` to show last modification date on the page header. The PR also add a partial `page-metadata` that can be overwritten to easily add custom page metadata.
Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/894

feat: add parameter geekdocPageLastmod

---

exampleSite/content/en/shortcodes/progress.md
exampleSite/data/properties/shortcode-progress.yaml
layouts/shortcodes/hint.html
layouts/shortcodes/progress.html
src/sass/_color_mode.scss
src/sass/_shortcodes.scss

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/852
This still does not allow setting custom colors, as I dont see a good way to pass vars down to CSS.

feat: support hint colors for progress shortcode

---

layouts/404.html
layouts/_default/baseof.html
layouts/partials/language.html
layouts/partials/site-header.html
src/js/accessibility.js
src/js/colorTheme.js
src/js/index.js
src/sass/_mobile.scss
webpack.config.js

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/987 and https://github.com/thegeeklab/hugo-geekdoc/issues/986
- Add Js to add keyboard handler for nav and header menu
This way the CSS only menu with checkboxes still work, while the menu toggles can also be used with keyboard navigation.
- Improve accessibility by setting aria labels and remove invisible/inactive content from tab index
To remove the invisible/inactive content from the tab index, `inert` was used, which should be supported on most modern browsers.

fix: support keyboard navigation for menus

---

layouts/partials/microformats/schema.html

I stumbled over this bug by reading the error message in https://github.com/thegeeklab/hugo-geekdoc/issues/1001.

fix: use site param geekdocLogo in microformats
