src/sass/_chroma_github.scss

remove white space between ln nos and code

---

exampleSite/content/usage/getting-started.md

Fix typo in getting-started.md

---

assets/js/search.js

fix broken flexsearch asset loading

---

exampleSite/config.yaml
exampleSite/content/toc-tree/level-1/_index.md
exampleSite/data/menu/main.yaml
layouts/partials/menu-bundle.html
layouts/partials/menu-filetree.html

Fixes https://github.com/thegeeklab/hugo-geekdoc/issues/51

feat: add collapsible sections to bundle menu

---

exampleSite/config.yaml
layouts/_default/_markup/render-heading.html
layouts/_default/_markup/render-image.html
layouts/_default/_markup/render-link.html
layouts/partials/content.html

Fixes https://github.com/thegeeklab/hugo-geekdoc/issues/54

fix: use custom render templates to fix references

---

layouts/shortcodes/columns.html
layouts/shortcodes/expand.html
layouts/shortcodes/hint.html
layouts/shortcodes/include.html
layouts/shortcodes/tabs.html

Fixes https://github.com/thegeeklab/hugo-geekdoc/issues/64

fix: replace markdownify with renderString to use render hooks

---

src/sass/_markdown.scss

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/74

fix: fix formatting of nested code blocks

---

src/sass/_base.scss

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/85

fix: fix broken search result links in WebKit browsers

---

.dictionary
exampleSite/content/usage/configuration.md
exampleSite/content/usage/getting-started.md

docs: add known limitations

---

assets/search-data.json
exampleSite/content/usage/configuration.md

Fixes: #95 
Upstream Issue: https://github.com/gohugoio/hugo/issues/7009

feat: add option geekdocProtected to exclude pages from data file

---

layouts/partials/head/others.html

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/125

fix: remove duplicate favicon declaration

---

exampleSite/content/shortcodes/columns.md

Supersedes: https://github.com/thegeeklab/hugo-geekdoc/pull/124

docs: improve wording of columns shortcode description

---

layouts/shortcodes/img.html

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/141

fix: fix rendering of nested img shortcodes

---

.dictionary
.drone.yml
.gitignore
.vnuignore
exampleSite/content/features/icon-sets.md
exampleSite/content/shortcodes/buttons.md
exampleSite/content/shortcodes/columns.md
exampleSite/content/shortcodes/expand.md
exampleSite/content/shortcodes/hints.md
exampleSite/content/shortcodes/icons.md
exampleSite/content/shortcodes/images/_index.md
exampleSite/content/shortcodes/includes.md
exampleSite/content/shortcodes/katex.md
exampleSite/content/shortcodes/mermaid.md
exampleSite/content/shortcodes/tabs.md
exampleSite/content/shortcodes/toc-tree.md
exampleSite/content/shortcodes/toc.md
exampleSite/content/toc-tree/_index.md
gulpfile.js
layouts/shortcodes/katex.html
package-lock.json
package.json
src/js/katex-loader.js
src/js/mermaid-loader.js

Supersedes: https://github.com/thegeeklab/hugo-geekdoc/pull/151

feat: add katex math typesetting shortcode

---

exampleSite/content/usage/configuration.md
layouts/partials/menu-filetree.html

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/227

feat: add site parameter `geekdocFileTreeSortBy` to control menu order

---

layouts/partials/posts/metadata.html
layouts/posts/list.html
layouts/posts/single.html
layouts/taxonomy/list.html
src/sass/_base.scss

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/260

feat: unify and always show post metadata

---

exampleSite/config.yaml
layouts/partials/search.html
src/js/search.js
webpack.config.js

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/286

fix: fix asset loading on subfolder deployments

---

src/sass/_asciidoc.scss
src/sass/_defaults.scss
src/sass/_test.scss
src/sass/main.scss

Related: https://github.com/thegeeklab/hugo-geekdoc/issues/378

fix: fix asciidoc sdmonitions formatting

---

i18n/it.yaml

As per title, adding Italian to i18n

Create Italian localization

---

layouts/shortcodes/hint.html

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/390

fix: fix nested hint rendering issues

---

layouts/partials/menu-bundle.html

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/385

fix: fix rendering issue for untranslated pages in bundle menu

---

.dictionary
exampleSite/content/en/features/code-blocks.md
exampleSite/content/en/shortcodes/propertylist.md
exampleSite/data/properties/demo.yaml
i18n/de.yaml
i18n/en.yaml
i18n/it.yaml
i18n/zh-cn.yaml
layouts/shortcodes/propertylist.html
src/sass/_chroma_base.scss
src/sass/_color_mode.scss
src/sass/_markdown.scss
src/sass/_shortcodes.scss

feat: add propertylist shortcode

---

exampleSite/content/en/shortcodes/mermaid.md
src/js/mermaid.js

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/424

chore: use mermaid default light and dark theme

---

exampleSite/content/en/shortcodes/columns.md
layouts/shortcodes/button.html

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/442

fix: fix broken rendering of nested buttons

---

exampleSite/content/en/usage/menus.md
layouts/partials/menu-bundle.html

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/467

feat: add option anchor the the bundle menu

---

package-lock.json
package.json

Required by `svgicons2svgfont` v12

chore: change min required node version to >=16.15 <=18

---

i18n/ja.yaml

Supersedes: https://github.com/thegeeklab/hugo-geekdoc/pull/471

feat: add ja language support

---

src/sass/_shortcodes.scss

Related to: https://github.com/mermaid-js/mermaid/issues/2481

fix: temp fix mermaid svg height

---

i18n/cs.yaml

Hey there!
We would like to start using Geekdoc for our docs, but unfortunatelly we need strict support for Czech language. So that's why I've decided to contribute to your project!
It should be pretty straight-forweard. I've used strictly formal language, but balanced the translations so it doesn't sound like a robot translated it.

feat: add cs language support

---

package-lock.json
package.json
webpack.config.js

Related: https://github.com/webdiscus/webpack-remove-empty-scripts/issues/10

fix: workaround an issue in webpack-remove-empty-scripts

---

i18n/ja.yaml
i18n/zh-cn.yaml

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/502

fix: fix css class in ja translation file

---

i18n/ja.yaml

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/504

fix: fix typo in ja translation file

---

.drone.yml
exampleSite/content/en/shortcodes/katex.md
exampleSite/content/en/shortcodes/mermaid.md
layouts/_default/_markup/render-codeblock-mermaid.html

Workaround related to: https://github.com/gohugoio/hugo/issues/10058

chore: bump hugo in ci to 0.104.3

---

exampleSite/content/en/asciidoc/admonitions.adoc
exampleSite/content/en/shortcodes/hints.md
src/sass/_asciidoc.scss

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/524

fix: fix multi paragraph admonitions formatting

---

i18n/cs.yaml
i18n/de.yaml
i18n/en.yaml
i18n/it.yaml
i18n/ja.yaml
i18n/zh-cn.yaml
layouts/_default/taxonomy.html
layouts/_default/terms.html
layouts/partials/pagination.html
layouts/posts/list.html
src/sass/_base.scss
src/sass/_print.scss

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/523

fix: add missing navigation for pagination

---

layouts/shortcodes/columns.html
layouts/shortcodes/tab.html
layouts/shortcodes/tabs.html

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/582

fix: fix rendering of nested shortcodes in tabs

---

layouts/shortcodes/columns.html

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/582

fix: issues with nested columns shortcode

---

exampleSite/content/en/shortcodes/progress.md
layouts/shortcodes/progress.html
src/sass/_shortcodes.scss

feat: add progress bar shortcode

---

i18n/nl.yaml

The site I am currently working on has only dutch content and I created a i18n translation file for the geekdoc functions.
It might benefit other users of the theme too, so I created this pull request with the nl.yaml file in it.

Added dutch translation for site functions.

---

exampleSite/content/en/usage/configuration.md

Documented weight sizing and negative being allowed

Standardized geekdoc casing, documented weight

---

exampleSite/content/en/usage/configuration.md
layouts/_default/baseof.html
layouts/partials/menu-bundle-np.html
layouts/partials/menu-filetree-np.html

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/720

feat: add next-prev navigation for filetree menu

---

package-lock.json
package.json
src/js/mermaid.js

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/741

fix: use selector loop to manually render all charts on a page

---

exampleSite/content/en/shortcodes/toc-tree.md
exampleSite/data/properties/shortcode-toc-tree.yaml
layouts/shortcodes/toc-tree.html

Partial fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/736

fix: respect `geekdocFileTreeSortBy` parameter while creating the toc tree

---

i18n/fr.yaml

feat: add french translation

---

exampleSite/content/en/shortcodes/hints.md
src/sass/_shortcodes.scss

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/838

feat: improve code block background color in hints

---

i18n/oc.yaml

feat: add oc language support 

---

exampleSite/content/en/features/theming/_index.md
exampleSite/static/custom.css.example
src/sass/_base.scss
src/sass/_defaults.scss
src/sass/_fonts.scss
src/sass/_shortcodes.scss
src/sass/main.scss

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/889

feat: add custom css properties to change fonts

---

i18n/da.yaml

I've translated all i18n strings to Danish.

Add Danish language translation

---

exampleSite/data/menu/main.yaml
layouts/partials/menu-bundle.html
layouts/partials/menu-extra.html

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/878

feat: add option to set rel attribute in bundle and extra menu

---

layouts/_default/baseof.html
layouts/_default/list.html
layouts/_default/single.html
layouts/_default/taxonomy.html
layouts/_default/terms.html
layouts/posts/list.html
layouts/posts/single.html
src/sass/_base.scss
src/sass/_utils.scss

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/972

feat: add skip-to-content link to improve accessability

---

src/js/accessibility.js

The accessibility helper was not working on desktop as the checkbox is not used there and the nav is always visible.

fix: fix accessibility helper for desktop

---

exampleSite/content/en/usage/configuration.md
layouts/partials/site-header.html
src/sass/_base.scss

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/995

feat: support brand subtitle

---

exampleSite/content/en/usage/customization.md
layouts/partials/head/custom.html

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/994

docs: document how to include custom resources

---

exampleSite/content/en/usage/configuration.md
src/sass/_markdown.scss

Fixes: https://github.com/thegeeklab/hugo-geekdoc/issues/1010

fix: apply overflow and max-height settings to raw code blocks
